# Generated by Django 4.0.1 on 2022-05-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='visualizacao',
            field=models.IntegerField(default=0),
        ),
    ]
